# If your compiler is based on CentOS8, use this dockerfile.

FROM centos:8
#MAINTAINER TenDB Development <jamxia@tencent.com>

RUN groupadd -r mysql -g 202 && useradd -m -r -g 202 -d /home/mysql -G users -u 30019 mysql


ENV CONTROL_VERSION tdbctl-test
ENV PATH=$PATH:/usr/local/mysql/bin
ENV MYSQLDIR=/usr/local/mysql MYSQLDATADIR=/data1/
ENV MYSQL_INIT_COMPLETE=${MYSQLDATADIR}/mysql_init_complete
ENV TERM=xterm
ENV TZ=Asia/Shanghai

COPY bin/gosu /usr/bin/gosu
COPY ${CONTROL_VERSION}-linux-x86_64.tar.gz ${CONTROL_VERSION}.tar.gz
COPY my.cnf /etc/my.cnf
COPY init-sql/* /docker-entrypoint-initdb.d/
COPY healthcheck.sh /usr/bin/healthcheck.sh
COPY ps-entry.sh /docker-entrypoint.sh

RUN rpm -ivh https://mirrors.tencent.com/centos/8/BaseOS/x86_64/os/Packages/publicsuffix-list-dafsa-20180723-1.el8.noarch.rpm \
    && rpm -ivh https://mirrors.tencent.com/centos/8/BaseOS/x86_64/os/Packages/libpsl-0.20.2-6.el8.x86_64.rpm \
    && rpm -ivh https://mirrors.tencent.com/centos/8/AppStream/x86_64/os/Packages/wget-1.19.5-10.el8.x86_64.rpm \
    && rm -rf /etc/yum.repos.d/* \
    # && mv /etc/yum.repos.d/CentOS-Linux-BaseOS.repo /etc/yum.repos.d/CentOS-Linux-BaseOS.repo.backup \
    # && wget -O /etc/yum.repos.d/CentOS-Linux-BaseOS.repo https://mirrors.tencent.com/repo/centos8_base.repo \
    # && wget -O /etc/yum.repos.d/CentOS-Linux-AppStream.repo https://mirrors.tencent.com/repo/centos8-stream.repo \
    # && wget -O /etc/yum.repos.d/CentOS-Linux-centos-vaultplus.repo https://mirrors.tencent.com/repo/centos8_vault_8.5.2111.repo \
    && wget -O /etc/yum.repos.d/CentOS-Linux-BaseOS.repo https://mirrors.tencent.com/repo/centos8_base.repo.bak \
    && yum clean all \
    && yum makecache \
    && yum install -y \
    numactl.x86_64 \
    libaio.x86_64 \
    && yum clean all \
    && rm -rf /var/cache/yum \
    && chmod +x /usr/bin/gosu \
    && gosu nobody true \
    && /usr/bin/install -m 0775 -o mysql -g root -d /usr/local/mysql ${MYSQLDATADIR} /docker-entrypoint-initdb.d \
    && tar xzf ${CONTROL_VERSION}.tar.gz -C ${MYSQLDIR} --strip-components=1 \
    && rm ${CONTROL_VERSION}.tar.gz \
    && chown -R mysql ${MYSQLDIR} \
    && chown -R mysql /docker-entrypoint.sh \
    && chown -R mysql /etc/my.cnf \
    && chmod +x /docker-entrypoint.sh \
    && chmod +x /usr/bin/healthcheck.sh

VOLUME ${MYSQLDATADIR}

ENTRYPOINT ["/docker-entrypoint.sh"]
HEALTHCHECK --interval=15s --timeout=5s CMD healthcheck.sh

EXPOSE 26000
CMD ["mysqld"]